### ISSUE TITLE
Packagist integration

### ISSUE THREAD

**Issue by mrsof** [CodeBoutique/price-rounder#1]
Hey dude !

I needed to import it inside my IDE but it wasn't available in [Packagist](https://packagist.org/packages/codeboutique/price-rounder).
So I created an account and registered your library.
I hope you agree with that. If not I'll remove it. Just tell me please.

Thanks for your work.

**Comment by mblarsen** [comment]
You can find it here https://packagist.org/packages/codeboutique/price-rounder thanks :)

UPDATE: Hmm, is that the one you created? Strange I'm sure it was there.

**Comment by mrsof** [comment]
No it wasn't. I looked for it before. :)

**Comment by mblarsen** [comment]
Thanks for adding it ;)

**Comment by mrsof** [comment]
My pleasure. You are welcome !

**Comment by mblarsen** [comment]
@mrsof can you add me to packagist.org so I can push new versions (or are they picked up automatically?)

**Comment by mrsof** [comment]
You are now maintainer

**Comment by mblarsen** [comment]
Thanks, I've set up auto-update webhook now.
